services:
  server:
    image: "hkmute/lunch-scheduler"
    depends_on:
      - db
    env_file: .env
    links:
      - db
    restart: always
  db:
    image: postgres:14
    restart: always
    env_file: .env
    volumes: 
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:stable-alpine
    restart: always
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    links:
      - server
    volumes:
        - "shared_run:/run"
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/templates:/etc/nginx/templates
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
        - "${EB_LOG_BASE_DIR}/nginx-docker:/var/log/nginx"
  nginx_reloader:
    image: nginx:stable-alpine
    pid: service:nginx
    depends_on:
      - nginx
    volumes:
      - "shared_run:/run"
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        while :; do
          sleep 6h
          echo reloading
          nginx -s reload
        done
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - "${EB_LOG_BASE_DIR}/letsencrypt-docker:/var/log/letsencrypt"
volumes:
  pgdata:
  shared_run: